datasource:
    user:
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/.backbase/poc/cxp6/userService;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE

spring:
    jpa:
        hibernate:
            hbm2ddl:
                auto: update
            dialect: org.hibernate.dialect.H2Dialect
            show_sql: true
