datasource:
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.backbase/poc/cxp6/userService;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
    poolSize: 2

spring:
    jpa:
        generate-ddl: true
        database: H2
        show-sql: true
        hibernate:
#            ddl-auto: create-drop
            ddl-auto: update
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy